# Generated by Django 4.0a1 on 2022-02-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_question',
            name='option1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_question',
            name='option2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_question',
            name='option3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_question',
            name='option4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
