# Generated by Django 4.0a1 on 2022-02-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_tbl_group_tbl_sop'),
        ('transaction', '0002_alter_tbl_question_option1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_practicalquestions',
            fields=[
                ('practicalquestions_id', models.AutoField(primary_key=True, serialize=False)),
                ('practical_questions', models.CharField(max_length=100)),
                ('showcode', models.FileField(upload_to='showcode')),
                ('output', models.FileField(upload_to='output')),
                ('cls_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.tbl_class')),
                ('grp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.tbl_group')),
                ('sop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.tbl_sop')),
            ],
        ),
    ]
