# Generated by Django 4.0a1 on 2022-02-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_sop',
            fields=[
                ('sop_id', models.AutoField(primary_key=True, serialize=False)),
                ('sop', models.CharField(max_length=100)),
                ('grp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.tbl_group')),
            ],
        ),
    ]
